# Site settings
title: Cool Breeze Bin
SEOTitle: CoolBreeze的博客 | Bin Blog
header-img: img/home-bg2.jpg
email: coolbreeze@petalmail.com
description: "一名有梦想的本科生 | CoolBreeze，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @CoolBreeze 的个人博客，与你一起发现更大的世界。"
keyword: "CoolBreeze, 技术分享, 热爱学术, 数据采集, 数据分析, 机器学习, 博客, 个人网站, 互联网, Web,前端"
url: "http://cool-breeze-bin.gitee.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     6068376350
# zhihu_username:     CoolBreeze
github_username:    Cool-breeze-bin
#twitter_username:   CoolBreeze
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]
# baidu_tongji_id: f3b06988f57795b0abce85993b9807fa
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me




# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "CoolBreeze，机器学习，数据采集，数据分析"
sidebar-avatar: img/myself.jpg # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
    #     title: "乱序（Midare）",
    #     href: "http://mida.re/"
    # },{
    #     title: "Sherry Woo",
    #     href: "https://sherrywoo.me/"
    # },{
    #     title: "Kun Qian",
    #     href: "http://kunq.me"
    # },{
    #     title: "Ebn Zhang",
    #     href: "http://ebnbin.com/"
    # },{
    #     title: "SmdCn",
    #     href: "http://blog.smdcn.net"
    # },{
    #     title: "JiyinYiyong",
    #     href: "http://tiye.me/"
    # },{
    #     title: "DHong Say",
    #     href: "http://dhong.co"
    # },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    }
]
